import '@/styles/globals.css';
import Head from 'next/head';

type Props = {
  children: React.ReactNode;
};

const RootLayout = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Collosal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <html lang="en">
        <body>{children}</body>
      </html>
    </>
  );
};

export default RootLayout;
