import '@/styles/globals.css';
import Head from 'next/head';
import { Noto_Sans } from 'next/font/google';

const font = Noto_Sans({
  subsets: ['latin'],
  display: 'swap',
  weight: ['700', '500', '400', '600'],
  variable: '--font-noto-sans',
});

type Props = {
  children: React.ReactNode;
};

const RootLayout = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Collosal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <html lang="en" className={font.className}>
        <body>{children}</body>
      </html>
    </>
  );
};

export default RootLayout;
